
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Oct 28 00:19:59 CEST 2016
//----------------------------------------------------

package compiler.syntax;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int RIGHT_BRACKET = 48;
  public static final int CONST = 12;
  public static final int ASSIGNMENT = 36;
  public static final int NOT_EQUAL = 40;
  public static final int INTEGER = 19;
  public static final int WRITEINT = 34;
  public static final int ARRAY = 9;
  public static final int PRODUCT = 5;
  public static final int FOR = 17;
  public static final int MINUS = 3;
  public static final int SEMICOLON = 44;
  public static final int NOT = 21;
  public static final int AND = 8;
  public static final int RECORD = 25;
  public static final int TYPE = 30;
  public static final int OR = 23;
  public static final int COMMA = 42;
  public static final int BEGIN = 10;
  public static final int RIGHT_PARENTHESIS = 46;
  public static final int PLUS = 2;
  public static final int WRITELN = 35;
  public static final int IF = 18;
  public static final int DOT = 41;
  public static final int OF = 22;
  public static final int BOOLEAN = 11;
  public static final int EOF = 0;
  public static final int RETURN = 26;
  public static final int EQUAL = 37;
  public static final int TRUE = 29;
  public static final int error = 1;
  public static final int MODULE = 20;
  public static final int COLON = 43;
  public static final int ELSE = 14;
  public static final int WRITESTRING = 33;
  public static final int TO = 28;
  public static final int WHILE = 32;
  public static final int THEN = 27;
  public static final int END = 15;
  public static final int STRING = 6;
  public static final int FALSE = 16;
  public static final int MORE_THAN = 39;
  public static final int DIVISION = 4;
  public static final int LESS_THAN = 38;
  public static final int LEFT_BRACKET = 47;
  public static final int VAR = 31;
  public static final int PROCEDURE = 24;
  public static final int LEFT_PARENTHESIS = 45;
  public static final int DO = 13;
  public static final int IDENTIFIER = 49;
  public static final int INTEGER_LITERAL = 7;
}

