
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Nov 22 17:15:47 CET 2016
//----------------------------------------------------

package compiler.syntax;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DIVIDE = 3;
  public static final int RIGHT_BRACKET = 40;
  public static final int CONST = 9;
  public static final int ASSIGNMENT = 29;
  public static final int NOT_EQUAL = 32;
  public static final int INTEGER = 15;
  public static final int WRITEINT = 27;
  public static final int SEMICOLON = 36;
  public static final int NOT = 17;
  public static final int AND = 6;
  public static final int RECORD = 19;
  public static final int TYPE = 23;
  public static final int COMMA = 34;
  public static final int BEGIN = 7;
  public static final int RIGHT_PARENTHESIS = 38;
  public static final int PLUS = 2;
  public static final int WRITELN = 28;
  public static final int IF = 14;
  public static final int DOT = 33;
  public static final int BOOLEAN = 8;
  public static final int EOF = 0;
  public static final int RETURN = 20;
  public static final int EQUAL = 30;
  public static final int TRUE = 22;
  public static final int error = 1;
  public static final int MODULE = 16;
  public static final int COLON = 35;
  public static final int ELSE = 11;
  public static final int WRITESTRING = 26;
  public static final int WHILE = 25;
  public static final int THEN = 21;
  public static final int END = 12;
  public static final int STRING = 4;
  public static final int FALSE = 13;
  public static final int LESS_THAN = 31;
  public static final int LEFT_BRACKET = 39;
  public static final int VAR = 24;
  public static final int PROCEDURE = 18;
  public static final int LEFT_PARENTHESIS = 37;
  public static final int DO = 10;
  public static final int IDENTIFIER = 41;
  public static final int INTEGER_LITERAL = 5;
}

